---
# Install lib-perl which is sometimes required for retrieving HTTPS URL's
- name: install package libwww-perl [Debian]
  apt: name=libwww-perl state=present
  when: "ansible_os_family == 'Debian'"

- name: install package perl-libwww-perl [RedHat]
  yum: name=perl-libwww-perl state=present
  when: "ansible_os_family == 'RedHat'"

# Install ipset if desired
- name: install package ipset
  package: name=ipset state=present
  when: "ipset|bool"

# Install perl GD Graph if desired
- name: install package libgd-graph-perl [Debian]
  apt: name=libgd-graph-perl state=present
  when: "statistical_graphs and ansible_os_family == 'Debian'"

- name: install package perl-GDGraph [RedHat]
  yum: name=perl-GDGraph state=present
  when: "statistical_graphs and ansible_os_family == 'RedHat'"

# Firewalld needs to be disabled to prevent bad stuff from happening with CSF in CentOS7
- name: Disable firewalld on [RedHat] and [CentOS7]
  service: name=firewalld state=stopped enabled=no
  register: disable_firewalld
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  failed_when: "disable_firewalld|failed and 'Could not find' not in disable_firewalld.msg"

# ifconfig (net-tools) needs to be installed for CSF to work properly in CentOS7
- name: install package net-tools [RedHat]
  yum: name=net-tools state=present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

# Extract tar.gz
- name: extract csf files
  unarchive: src=https://download.configserver.com/csf.tgz dest=/usr/src/ creates=/usr/src/csf/LICENSE.txt copy=no

# Install CSF
- name: install csf
  shell: /usr/src/csf/install.sh chdir=/usr/src/csf creates=/etc/csf/csf.conf
  register: result
