---

- name: ensure file exists
  copy:
    content: ""
    dest: /etc/csf/includes/whitelist.allow
    force: no
    group: root
    owner: root
    mode: 0644

# White list ips
- name: Whitelist IPs
  lineinfile: >
    dest="/etc/csf/includes/whitelist.allow"
    regexp="^{{ item }}$"
    line="{{ item }}"
  with_flattened:
    - "{{ csf_allow_hosts }}"
    - "{{ csf_global_allow_hosts }}"
  notify: restart csf

# Enable rules in csf.allow
- name: enable common csf.allow rules
  lineinfile: >
    dest="/etc/csf/csf.allow"
    regexp="^Include /etc/csf/includes/whitelist.allow$"
    line="Include /etc/csf/includes/whitelist.allow"
  when: csf_allow_hosts|length > 0 or csf_global_allow_hosts|length >0
  notify: restart csf
